mayadata-io/oep-e2e

litmus/director/openebs-upgrade-jiva/run_litmus_test.yml
litmus/director/openebs-upgrade-jiva/test.yml
litmus/director/openebs-upgrade-jiva/test_vars.yml

- Changed job name for openebs-jiva-upgrade

(bug):Changed job name for openebs-jiva-upgrade

---

litmus/director/openebs-control-plane-test/run_litmus_test.yml
litmus/director/openebs-data-plane-test/run_litmus_test.yml
litmus/director/openebs-install/run_litmus_test.yml
litmus/director/openebs-self-install/run_litmus_test.yml
litmus/director/openebs-upgrade-jiva/run_litmus_test.yml

- Added oep-secret in job files

Added oep-secret in job files

---

litmus/director/openebs-resource-limit-installation/README.md
litmus/director/openebs-resource-limit-installation/run_litmus_test.yml
litmus/director/openebs-resource-limit-installation/test.yml
litmus/director/openebs-resource-limit-installation/test_vars.yml

Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>
- Install OpenEBS using custom resource limits

[iuoi14]: Install OpenEBS using custom resource limits

---

litmus/director/upgrade-all-replica-pod-pending/README.md
litmus/director/upgrade-replica-pod-pending/README.md

- Added readme for test cases.

Added readme for upgrade application when replicas are not in running state

---

.master-plan.yml

We will be using this as a base file. Later it would be updated to platform-specific repo
Signed-off-by: ajeshbaby <ajesh.baby@mayadata.io>

Initial commit

---

litmus/director/tcid-iuod08-pool-upgrade/run_litmus_test.yml
litmus/director/tcid-iuod12-volume-upgrade/run_litmus_test.yml
litmus/director/tcid-iuod27-volume-upgrade-jiva/run_litmus_test.yml
litmus/director/tcid-iuod28-upgrade-replica-pod-pending/run_litmus_test.yml
litmus/director/tcid-iuod29-upgrade-two-replica-pod-pending/run_litmus_test.yml
litmus/director/tcid-iuod30-upgrade-all-replica-pod-pending/run_litmus_test.yml
litmus/director/tcid-iuoi01-openebs-self-install/run_litmus_test.yml
litmus/director/tcid-iuoi02-openebs-install/run_litmus_test.yml
litmus/director/tcid-iuoi03-openebs-control-plane/run_litmus_test.yml
litmus/director/tcid-iuoi04-openebs-data-plane/run_litmus_test.yml
litmus/director/tcid-iuoi06-openebs-reinstallation/run_litmus_test.yml
litmus/director/tcid-iuoi14-openebs-resource-limit-installation/run_litmus_test.yml

- Added new path in litmus job

Changed path in args of litmus job

---

litmus/director/cassandra/README.md
litmus/director/cluster-connect-check/README.md
litmus/director/configs-db/README.md
litmus/director/consul/README.md
litmus/director/ingress-nginx/README.md
litmus/director/maya-io-server/README.md
litmus/director/maya-ui/README.md
litmus/director/mysql/README.md
litmus/director/openebs-control-plane-test/README.md
litmus/director/openebs-data-plane-test/README.md
litmus/director/openebs-self-install/README.md
litmus/director/openebs-upgrade-jiva/README.md
litmus/director/volume-upgrade/README.md

- Added readme.md file in oep repo.

Added readme of jobs in oep repo

---

.master-plan.yml
Contributing-Guidelines.md
master-plan.md

Adding TCs for 
- cstor pool provisioing 
- gui Automation

Testplan update with cstor pool provisioning and PO Gui Automation TCs

---

utils/openebs-cleanup.yml
utils/openebs-label-cleanup.yml

- Indentation fix for clean-up tasks

(Fix): Indentation fix for cleanup tasks

---

litmus/director/tcid-iuoi01-openebs-self-install/test.yml
litmus/director/tcid-iuoi02-openebs-install/test.yml

- Added node_id[ ] into the openebs install into connected cluster test yml
- This node_id[ ] will be used in openebs-label-clean-up.yml file

Fix: added node_id[] in the test openebs install test

---

utils/openebs-label-cleanup.yml

- Added node name in clean-up task

(Fix):Added node name in clean-up task

---

utils/openebs-cleanup.yml

- Added task to check openebs components are deleted or not.

[fix]Added task to check openebs components are deleted or not

---

utils/openebs-cleanup.yml

(Fix): Added delete pods/jobs task in clean-up of openenbs

---

utils/result_update.py

- Modified the python script .
- Added `job_name` in the script.
- Changed directory path.

Added python script to update readme.md

---

litmus/director/admin-create-apikey/test.yaml

Signed-off-by: harshita-sharma011 <harshita.sharma@mayadata.io>
```
```

remove port from director url

---

litmus/director/admin-cluster-connect/run_litmus_test.yml

Renamed job name of admin-cluster-connect

---

litmus/director/admin-cluster-connect/test.yaml
litmus/director/admin-create-apikey/test.yaml

Added port in director_url file

---

.master-plan.yml
master-plan.md

Test plan updation
- fix the TC IDs for Teaming
- GUI Automation
- Authentication Tests

[chore]  [WIP] Testplan updation

---

utils/openebs-cleanup.yml

- Added new task to verify openebs is removed or not from cluster.

Added new  task to verify  that openebs is removed from cluster.

---

.travis.yml
testplan/Dockerfile

chore(travis): push testplan image to dockerhub

---

utils/openebs-cleanup.yml

Removed jinja template from task

---

utils/openebs-cleanup.yml

Removed typo

---

utils/openebs-cleanup.yml

(fix): Removed clusterComponents from task Fetching specific component details to verify

---

litmus/director/tcid-iuoi02-openebs-install/test.yml
litmus/director/tcid-iuoi03-openebs-control-plane/test.yml

Fix for openebs job in test case

---

testplan/Dockerfile
testplan/docusaurus.config.js
testplan/nginx-custom.conf
testplan/src/pages/index.js

Signed-off-by: Uma Mukkara <uma@mayadata.io>

Adding content to the front page of testplan website

---

testplan/docs/gitlabstages.md
testplan/docs/testbed.md
testplan/docusaurus.config.js
testplan/sidebars.js

Signed-off-by: Uma Mukkara <uma@mayadata.io>

adding gitlabstages recommendations and fixing the edit page

---

litmus/director/tcid-iuoi01-openebs-self-install/test.yml
litmus/director/tcid-iuoi02-openebs-install/test.yml

- Removed hard coded values.
- Refactored openebs check logic 

Removed hard-coded values and get refactored openebs check logic

---

testplan/docs/getstarted.md
testplan/docs/gitlabstages.md

Signed-off-by: Uma Mukkara <uma@mayadata.io>

Update gitlab stages files

---

litmus/director/tcid-iuoi01-openebs-self-install/test.yml
litmus/director/tcid-iuoi02-openebs-install/test.yml
litmus/director/tcid-iuoi03-openebs-control-plane/test.yml
litmus/director/tcid-iuoi04-openebs-data-plane/test.yml
litmus/director/tcid-iuoi14-openebs-resource-limit-installation/test.yml

- Changed body of openebs job POST request
- Changed URL to fetch openebs job details.
- Added few more checks
- Increased and delay for few tasks

Changed URL of some tasks and also changed body of openebs jobs in installation test-cases

---

litmus/director/tcid-iuoi01-openebs-self-install/run_litmus_test.yml

- Added openebs namespaces in job yml

Added openebs namespace in job for self connected cluster

---

testplan/docs/director/installation/directorInstall.md
testplan/docs/director/installation/install-gcp-tcid-1240.md
testplan/docs/director/installation/install-gcp-tcid-iudi01.md
testplan/docs/gitlabstages.md
testplan/sidebars.js

Instead of wil it should be will
```
```

Fixed the typo

---

litmus/director/account-access/cluster-account/README.md
litmus/director/account-access/project-account/README.md

Adds README.md for projectaccount and clusteraccount access testcases
```
```

Add README.MD to account-access testcases

---

litmus/director/tcid-iuoi01-openebs-self-install/test.yml
litmus/director/tcid-iuoi02-openebs-install/test.yml
utils/openebs-cleanup.yml

- Refactored openebs install job and added blocks into the test case.
- Removed app ns from clean-up task

Refactored openebs install test case and refactored clean-up tasks .

---

litmus/director/tcid-iuoi02-openebs-install/test.yml
utils/app-cleanup.yml

- Added separate util to delete application .
- Included this util file in openebs_install job to delete application ns.

(Bug-fix):Added separate util for application deletion

---

litmus/director/tcid-iuoi04-openebs-data-plane/test.yml

Refactored openebs-install-data-plane test case

---

litmus/director/tcid-iuoi03-openebs-control-plane/test.yml

Refactored openebs control plane test case

---

litmus/director/tcid-iuoi03-openebs-control-plane/test.yml
litmus/director/tcid-iuoi04-openebs-data-plane/test.yml

Removed typo from control plane and data plane test cases

---

litmus/director/tcid-iuoi03-openebs-control-plane/test.yml
litmus/director/tcid-iuoi04-openebs-data-plane/test.yml

(Fix): Fix for data-plane and control plane test cases

---

litmus/director/tcid-iuoi03-openebs-control-plane/test.yml
litmus/director/tcid-iuoi04-openebs-data-plane/test.yml

- Fetching namespace where openebs is installed and pass the value to openebs-clean-up tasks.

(Fix): Getting namespace for openebs clean-up tasks

---

litmus/director/tcid-iuoi03-openebs-control-plane/test.yml
litmus/director/tcid-iuoi04-openebs-data-plane/test.yml
litmus/director/tcid-iuoi06-openebs-reinstallation/test.yml
litmus/director/tcid-iuoi14-openebs-resource-limit-installation/test.yml

- Refactored openebs-reinstallation-check 
- Renamed few variable names.

Refactored openebs reinstallation test case

---

litmus/director/tcid-iuoi06-openebs-reinstallation/run_litmus_test.yml
litmus/director/tcid-iuoi06-openebs-reinstallation/test.yml
litmus/director/tcid-iuoi14-openebs-resource-limit-installation/test.yml

- Added Added `imagePullSecrets` in openebs-reinstallation job 
- Removed few typos

Added imagePullSecrets in openebs-reinstallation job and removed some typos

---

litmus/director/tcid-iuoi14-openebs-resource-limit-installation/run_litmus_test.yml
litmus/director/tcid-iuoi14-openebs-resource-limit-installation/test.yml

- Refactored test file.
- Increased delay and retries

Refactored resource limit openebs installation job

---

litmus/director/tcid-iuoi14-openebs-resource-limit-installation/test.yml

Changed kubectl command to check openebs is already present or not

---

testplan/docs/director/openebs/TC-CSP-REC-CREATE-MIRROR.md
testplan/docs/director/openebs/TC-CSP-REC-CREATE-STRIPE.md
testplan/docs/director/openebs/TC-CSP-REC-LIST-MIRROR.md
testplan/docs/director/openebs/TC-CSP-REC-LIST-NO-NDM.md
testplan/docs/director/openebs/TC-CSP-REC-LIST-STRIPE.md
testplan/docs/director/openebs/TC-CSP-REC-LIST.md
testplan/docs/director/openebs/directorOpenEBS.md
testplan/sidebars.js

feat(csp): update cstor pool recommendation tests

---

litmus/director/tcid-iuoi14-openebs-resource-limit-installation/test.yml

- Giving POST request on `action=selectopenebsnodes` to label nodes.

Using selectopenebsnodes to label the nodes

---

litmus/director/tcid-iuod12-volume-upgrade/run_litmus_test.yml
litmus/director/tcid-iuod12-volume-upgrade/test.yml
litmus/director/tcid-iuod24-pool-upgrade-one-pod-not-running/run_litmus_test.yml
litmus/director/tcid-iuod26-pool-upgrade-all-pod-not-running/run_litmus_test.yml
litmus/director/tcid-iuod26-pool-upgrade-all-pod-not-running/test.yml

- Refactored all openebes upgrade-jobs 
- changes the version of few upgrade jobs
**Note for Reviewer**
- Dependent PR: https://github.com/mayadata-io/oep-e2e-gcp/pull/105

Refactored all openebs upgrade jobs

---

litmus/director/tcid-iuod12-volume-upgrade/run_litmus_test.yml
litmus/director/tcid-iuod12-volume-upgrade/test_vars.yml
litmus/director/tcid-iuod23-pool-upgrade-all-pod-running/run_litmus_test.yml
litmus/director/tcid-iuod24-pool-upgrade-one-pod-not-running/run_litmus_test.yml
litmus/director/tcid-iuod26-pool-upgrade-all-pod-not-running/run_litmus_test.yml
litmus/director/tcid-iuod27-volume-upgrade-jiva/run_litmus_test.yml
litmus/director/tcid-iuod28-upgrade-replica-pod-pending/run_litmus_test.yml
litmus/director/tcid-iuod29-upgrade-two-replica-pod-pending/run_litmus_test.yml
litmus/director/tcid-iuod30-upgrade-all-replica-pod-pending/run_litmus_test.yml

- Added namespace in all openebs upgrade jobs

(Fix)Added namaspace in openebs upgrade jobs

---

testplan/docs/director/installation/directorInstall.md
testplan/docs/director/installation/tc-upgrade-gpd-std.md
testplan/docs/director/installation/tc-upgrade-ssd-cstor.md
testplan/docs/director/installation/tc-upgrade-ssd-lpv.md
testplan/sidebars.js

test cases for dop upgrade

---

utils/result_update.py

- This PR intends to update the repo in which the e2e-results will be stored in `result_update.py` python script.
N/A
N/A
N/A
N/A
N/A
N/A
```
```

Update e2e-results repo

---

litmus/director/tcid-iuod12-volume-upgrade/test.yml

- Increased delay in volume upgrade test case

Increased delay in volume upgrade test case

---

testplan/docs/director/installation/tc-install-gpd-std.md

- This PR intends to include the test result link in `tc-install-gpd-std.md` file.
```
```

Add test-results link in tc-install-gpd-std

---

litmus/director/tcid-iuod12-volume-upgrade/test.yml

- Refactored volume upgrade test cases
- Increased delay and retries

Refactored volume-upgrade test case

---

litmus/director/tcid-iuod12-volume-upgrade/test.yml

(fix)Change value 0f data for mayastoragepools

---

litmus/director/tcid-iuod23-pool-upgrade-all-pod-running/test.yml

(Fix): Removed typo from test file pool upgrade all pod running

---

litmus/director/tcid-iuod23-pool-upgrade-all-pod-running/test_vars.yml
litmus/director/tcid-iuod24-pool-upgrade-one-pod-not-running/test_vars.yml

- Changed job name of few upgrade jobs

(Fix)Changed job name for upgrade jobs in vars file

---

litmus/director/tcid-iuod24-pool-upgrade-one-pod-not-running/test.yml
litmus/director/tcid-iuod26-pool-upgrade-all-pod-not-running/test.yml

- Added stdout for username and password

Added stdout for username and password

---

litmus/director/tcid-iuod26-pool-upgrade-all-pod-not-running/test.yml
litmus/director/tcid-iuod26-pool-upgrade-all-pod-not-running/test_vars.yml
litmus/director/tcid-iuod27-volume-upgrade-jiva/test.yml
litmus/director/tcid-iuod27-volume-upgrade-jiva/test_vars.yml
litmus/director/tcid-iuod28-upgrade-replica-pod-pending/run_litmus_test.yml
litmus/director/tcid-iuod28-upgrade-replica-pod-pending/test.yml
litmus/director/tcid-iuod28-upgrade-replica-pod-pending/test_vars.yml
litmus/director/tcid-iuod29-upgrade-two-replica-pod-pending/test.yml
litmus/director/tcid-iuod30-upgrade-all-replica-pod-pending/test.yml
utils/install-openebs.yml
utils/mongo-app.yml
utils/mongodb-app.yml
utils/pvc.yml

- First added clean-up task in TCID-26 to remove openebs from cluster
- Installed openebs of version 1.6.0 in TCID-28
- Also deployed mongo-db application in the cluster and used jiva storage
- Created seperate utils to create mongodb application
- Increased delay and retries in multiple upgrade jobs 

Refactored all the upgrade jobs so that they run properly

---

litmus/director/tcid-iuoc01-control-plane-upgrade/test.yml
utils/mongo-app.yml

- Changed file directory to deploy application in upgrade jobs
- Fixed typo from control plane upgrade test file
signed-off-by: Amit Bhatt <amitbhatt818@gmail.com>

Changed file directory to deploy application in upgrade jobs

---

litmus/director/tcid-iuod27-volume-upgrade-jiva/test.yml
litmus/director/tcid-iuod28-upgrade-replica-pod-pending/test.yml
litmus/director/tcid-iuod29-upgrade-two-replica-pod-pending/test.yml
litmus/director/tcid-iuod30-upgrade-all-replica-pod-pending/test.yml

- Changes status of volume replica pods from Healthy to Running
- Added post checks to check the status of volume replica pods

Changes status of volume replica pods from Healthy to Running and added pre-checks

---

litmus/director/tcid-iuod29-upgrade-two-replica-pod-pending/test.yml
litmus/director/tcid-iuod29-upgrade-two-replica-pod-pending/test_vars.yml
litmus/director/tcid-iuod30-upgrade-all-replica-pod-pending/test.yml
litmus/director/tcid-iuod30-upgrade-all-replica-pod-pending/test_vars.yml

- Replica pod health check for volume replica pods

Added health check for all replica pods

---

litmus/director/tcid-iuod29-upgrade-two-replica-pod-pending/test.yml

Removed extra task from test file

---

litmus/director/tcid-iuod30-upgrade-all-replica-pod-pending/test.yml

Changed index value of volume replica pods

---

litmus/director/tcid-iuod27-volume-upgrade-jiva/test.yml

- Added new check for version in test file

Added check for version

---

litmus/director/tcid-iuod27-volume-upgrade-jiva/test.yml

- Added check for application volume upgrade job status

Added check for application volume upgrade job status

---

litmus/director/tcid-cpre01-list-recommendations/run_litmus_test.yml
litmus/director/tcid-cpre01-list-recommendations/test_vars.yml
litmus/director/tcid-cpre02-device-recommendation/run_litmus_test.yml
litmus/director/tcid-cpre02-device-recommendation/test_vars.yml
litmus/director/tcid-ppcp01-create-cstor-pool/run_litmus_test.yml
litmus/director/tcid-ppcp01-create-cstor-pool/test_vars.yml

Added ns for cstorpool recommendation test cases

---

testplan/docs/openebs-enterprise/openebs/OpenEBS-Enterprise.md
testplan/sidebars.js

[chore] TOC update

---

scripts/director-health-check.sh
scripts/director-health-checks/alertmanager-check.sh
scripts/director-health-checks/alertstore-check.sh
scripts/director-health-checks/alertstore-tablemanager-check.sh
scripts/director-health-checks/cassandra-check.sh
scripts/director-health-checks/chat-server-check.sh
scripts/director-health-checks/cloud-agent-check.sh
scripts/director-health-checks/configs-check.sh
scripts/director-health-checks/configs-db-check.sh
scripts/director-health-checks/consul-check.sh
scripts/director-health-checks/distributor-check.sh
scripts/director-health-checks/ingester-check.sh
scripts/director-health-checks/ingress-nginx-check.sh
scripts/director-health-checks/maya-grafana-check.sh
scripts/director-health-checks/maya-io-server-check.sh
scripts/director-health-checks/maya-ui-check.sh
scripts/director-health-checks/memcached-check.sh
scripts/director-health-checks/mysql-check.sh
scripts/director-health-checks/od-elasticsearch-check.sh
scripts/director-health-checks/od-kibana-check.sh
scripts/director-health-checks/querier-check.sh
scripts/director-health-checks/ruler-check.sh

This PR intends to do the folowing:
- Add director-health-check scripts.
The following `Rancher` pipeline ran successfully with the below changes --
- https://gitlab.mayadata.io/oep/oep-e2e-rancher/pipelines/8869
```
```

Add director-health-check scripts

---

scripts/director-health-check.sh
scripts/director-health-checks/alertmanager-check.sh
scripts/director-health-checks/alertstore-check.sh
scripts/director-health-checks/alertstore-tablemanager-check.sh
scripts/director-health-checks/cassandra-check.sh
scripts/director-health-checks/chat-server-check.sh
scripts/director-health-checks/cloud-agent-check.sh
scripts/director-health-checks/configs-check.sh
scripts/director-health-checks/configs-db-check.sh
scripts/director-health-checks/consul-check.sh
scripts/director-health-checks/distributor-check.sh
scripts/director-health-checks/ingester-check.sh
scripts/director-health-checks/ingress-nginx-check.sh
scripts/director-health-checks/maya-grafana-check.sh
scripts/director-health-checks/maya-io-server-check.sh
scripts/director-health-checks/maya-ui-check.sh
scripts/director-health-checks/memcached-check.sh
scripts/director-health-checks/mysql-check.sh
scripts/director-health-checks/od-elasticsearch-check.sh
scripts/director-health-checks/od-kibana-check.sh
scripts/director-health-checks/querier-check.sh
scripts/director-health-checks/ruler-check.sh

This PR updates the director-health-check scripts with the `oep-e2e` in place of `oep`.
Pipeline that ran successfully with the below changes -
- https://gitlab.mayadata.io/oep/oep-e2e-konvoy/pipelines/9104

Update path of oep with oep-e2e in director-health-check script

---

testplan/src/pages/index.js

Fix a type for Kubernetes SRE on the landing page of e2e.mayadata.io

---

testplan/docs/gitlabstages.md
testplan/docs/testbed.md

Updated Testbed for Rancher and AWS

feat(testplan): update pipeline and testbed details

---

testplan/docs/getstarted.md

feat(testplan): update introduction page

---

testplan/docusaurus.config.js
testplan/src/css/custom.css

Signed-off-by: isamrish <askmaurya48@gmail.com>
This commit will update font-family to `Comfortaa` in e2e testing docs
**After applying new font**

feat(Docs): Update font family to `Comfortaa`

---

testplan/docs/director/dmaas/dmaas.md
testplan/docs/openebs-enterprise/dao/dao.md
testplan/docs/openebs-enterprise/openebs/openebs.md

feat(testplan): add test strategies w.r.t dmaas, dao, openebs ee

---

testplan/docs/openebs-enterprise/openebs/openebs.md

feat(testplan): add soak, scalability test plans for OEE

---

testplan/docs/gitlabstages.md

feat(testplan): update cluster setup details

---

testplan/docs/openebs-enterprise/openebs/openebs.md

feat(testplan): add soak & scalability tests for local zfs

---

litmus/director/tcid-iuoi02-openebs-install/test.yml
litmus/director/tcid-iuoi03-openebs-control-plane/test.yml

- Removed openebs cleanup code from ending of the job `tcid-iuoi02-openebs-install`
- And added openebs clean-up at the starting of job `tcid-iuoi03-openebs-control-plane`

Removed openebs cleanup code from ending of the job

---

litmus/director/tcid-iuoi02-openebs-install/test.yml

- Added check for cleanup task in install job

Added check for cleanup task

---

master-plan.md

chore(glossary): update testcase id glossary

---

testplan/docs/pipelines.md

feat(pipelines): update pipelines & related stages

---

litmus/director/tcid-ppcp01-create-cstor-pool/run_litmus_test.yml
litmus/director/tcid-ppcp01-create-cstor-pool/test.yml

- Removed task to check pool pods

Removed tasks to check pool pod status

---

litmus/director/tcid-ppcp01-create-cstor-pool/test.yml

- Removed typo from cstor pool creation test case.

Removed typo from pool recommendation test case

---

litmus/director/tcid-ppcp01-create-cstor-pool/test.yml

- Fetching devicegroupname from capacity-recommendation-list 
- Passing device_groupName to get device recommendation.

Fetch deviceGroupName from capacity-recommendation list

---

testplan/docs/pipelines.md
testplan/docs/testbed.md

chore(pipelines): categorize pipelines clusters as groups

---

litmus/director/tcid-ppcp01-create-cstor-pool/test.yml

- Changed status code for GET and POST request

Changes status code for cstor pool recommendation

---

litmus/director/tcid-iuoi02-openebs-install/test.yml
litmus/director/tcid-ppcp01-create-cstor-pool/test.yml

- Introduced delay in cstor-pool creation step
- Introduced new check to wait until the data populates in the openebs

Introduced new check to wait until the data populates in the openebs

---

litmus/director/tcid-iuoi02-openebs-install/test.yml

Fix indentation of task

---

litmus/director/tcid-iuoi02-openebs-install/test.yml
litmus/director/tcid-ppcp01-create-cstor-pool/test.yml

Added 2 min pause in the job

---

litmus/director/tcid-ppcp01-create-cstor-pool/test.yml

Convert json object to string

---

litmus/director/tcid-ppcp01-create-cstor-pool/test.yml

Changed format of body

---

testplan/docs/director/dmaas/dmaas.md

feat(dmaas): add mysql, cortex & portal testplans

---

testplan/docs/director/authentication/authentication.md

fix(authentication): include correct auth providers in testplan

---

litmus/director/TCID-DIR-OP-CSP-REC-LIST-NO-NDM/README.md
litmus/director/TCID-DIR-OP-CSP-REC-LIST-NO-NDM/run_litmus_test.yml
litmus/director/TCID-DIR-OP-CSP-REC-LIST-NO-NDM/test.yml
litmus/director/TCID-DIR-OP-CSP-REC-LIST-NO-NDM/test_vars.yml

- List cstor pool recommendations without NDM
**_Details:_**
- NDM should not be running
- Director should list the supported recommendations without error
- Director should list the capacity based recommendations without error
- Director should list the device based recommendations without error
| --- | --- | …

[TCID-DIR-OP-CSP-REC-LIST-NO-NDM]:List cstor pool recommendations without NDM

---

testplan/docs/director/openebs-provisioning/provisioning.md

feat(openebs): update director openebs provisioning test cases

---

litmus/director/tcid-iuoc03-control-plane-upgrade-higher-version-data-plane/README.md
litmus/director/tcid-iuoc03-control-plane-upgrade-higher-version-data-plane/run_litmus_test.yml
litmus/director/tcid-iuoc03-control-plane-upgrade-higher-version-data-plane/test.yml
litmus/director/tcid-iuoc03-control-plane-upgrade-higher-version-data-plane/test_vars.yml

- Upgrade of control plane(1.6) which is lower version of Data plane (1.7)
**_Details:_**
**_Steps involved:_**
- Also check the status of all the Data-Plane and Control-Plane components they should be in running state.
**Steps involved in the test case**
- Get active openebs record from v3/groups/{gropu_id}/cluster/{cluster_id}/openebs/{openebs_id}
- After that trigger action upgradecontrolplane. Once we triggered the action with the target version as input.
- This should result into a `InvalidAction`
- Control plane upgrade should not proceed.
| --- | --- |
|Assumptions | openebs should be already …

[tcid-iuoc03] Upgrade of control plane(1.6) which is lower version of Data plane (1.7)

---

testplan/docs/director/dmaas/dmaas.md

feat(dmaas): add psp & secret related dmaas testplans

---

.master-plan.yml
testplan/docs/director/dmaas/dmaas.md

feat(master yaml): add dmaas & openebs TCIDs to master test plan yaml

---

testplan/docs/testbed.md

This PR intends to add Konvoy cluster details (C1 and C2) in the Testbed.

Add Konvoy cluster details in Testbed

---

.master-plan.yml
testplan/docs/director/installation/installation.md

feat(director): add testplans w.r.t director install on persistent disks

---

.master-plan.yml
testplan/docs/director/dmaas/dmaas.md

feat(dmaas): add ml, data movement, source unavailable testplans

---

litmus/director/tcid-iuoi03-openebs-control-plane/test.yml

- Adde pre check for openebs uninstall 
- Added pre check for node label clean-up

Added precheck for openebs uninstall and label-cleanup

---

litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE/test.yml

- Removed pause from test file

Removed pause from test file

---

litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE/test.yml
litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-MIRROR/test.yml

- Added pause in create cstor pool job.

Reverted the change and added pause in test file

---

testplan/docs/director/dmaas/TCID-DIR-DMAAS-SCHD-CSTOR-AWS-BUCKET.md
testplan/docs/director/dmaas/TCID-DIR-DMAAS-SCHD-CSTOR-MINIO-BUCKET.md
testplan/docs/director/dmaas/TCID-DIR-DMAAS-SCHD-JIVA-AWS-BUCKET.md
testplan/docs/director/dmaas/TCID-DIR-DMAAS-SCHD-JIVA-MINIO-BUCKET.md
testplan/docs/director/dmaas/TCID-DIR-DMAAS-SCHD-LOCAL-DEV-AWS-BUCKET.md
testplan/docs/director/dmaas/TCID-DIR-DMAAS-SCHD-LOCAL-DEV-MINIO-BUCKET.md
testplan/docs/director/dmaas/TCID-DIR-DMAAS-SCHD-LOCAL-HP-AWS-BUCKET.md
testplan/docs/director/dmaas/TCID-DIR-DMAAS-SCHD-LOCAL-HP-MINIO-BUCKET.md
testplan/sidebars.js

Dmaas readme file updated for backup and restore using DOP of minio application deployed on source cluster using different storage class like Jiva, cStor, hostpath , device  and cloud bucket used are AWS and Minio
```

Dmaas readme file updated

---

testplan/docs/director/openebs-provisioning/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-MIRROR.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-MIRROR.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-NO-NDM.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-STRIPE.md

- Added test result readme link in test plan. 

Added result readme link in test plan md

---

testplan/docs/pipelines.md

The DOP images which are run in the pipeline are taken from director-charts-internal repo
```
```

Added the director charts internal repo info in pipeline doc

---

.master-plan.yml
testplan/docs/director/authentication/authentication.md
testplan/docs/director/dmaas/dmaas.md
testplan/docs/director/installation/installation.md
testplan/docs/director/openebs-provisioning/provisioning.md

feat(testplan): add dmaas, auth and dop based openebs install cases

---

litmus/director/TCID-DIR-INSTALL-ON-LOCAL-HP/README.md

- PR contains the TCID-DIR-INSTALL-ON-LOCAL-HP Test case Details 
Issue :
https://github.com/mayadata-io/oep-e2e/issues/539

Add TCID-DIR-INSTALL-ON-LOCAL-HP Test case Readme

---

litmus/director/TCID-DIR-OP-CSTOR-POOL-MIRROR-RECOMMEND-REBOOT-NODE/test.yml

- Removed typo from test case.

Removed typo from test case

---

.master-plan.yml
testplan/docs/director/openebs-provisioning/provisioning.md

feat(testplan): add cstor, jiva upgrade testplans

---

utils/openebs-cleanup.yml

-  Added check for openebses status after removing openebs

Added check for openebses status after cleanup

---

.master-plan.yml

- Added openebs install jobs in master plan yml

Added openebs install tcid in master plan yml

---

.master-plan.yml

- GUI Profile tcid update in master-plan.yml
```
```

GUI Profile TCID update

---

.master-plan.yml

- Added cstor pool deletion test cases in master.yml
` [TCID-DIR-OP-DELETE-SPC-WITH-VOLUME]`
`[TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-VOLUME]`
`[TCID-DIR-OP-DELETE-SPC-WITH-NO-VOLUME]`
`[TCID-DIR-OP-DELETE-CSPC-WITH-VOLUME]`
`[TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-NO-VOLUME]`
`[TCID-DIR-OP-DELETE-CSPC-WITH-NO-VOLUME]`

Added cstor pool deletion test cases in master.yml

---

testplan/docs/director/openebs-provisioning/TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-INSTALL-OPENEBS-LIMIT-RESOURCE.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-INSTALL-OPENEBS.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-RE-INSTALL-OPENEBS.md
testplan/sidebars.js

-Added readme.md files for all the openebs install test cases.

Added readme files for all the install jobs in test plan site

---

utils/openebs-cleanup.yml

Added check for cleaning SPC

---

.master-plan.yml

Director teaming TCID updated for user invite, user role update positive as well as negative test cases.

Teaming TCID updated

---

utils/openebs-cleanup.yml

- Added 20 sec pause in openebs cleanup task

Introduced wait in openebs cleanup task

---

litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE/run_litmus_test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE/test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE/run_litmus_test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE/test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS/run_litmus_test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS/test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS/test_vars.yml
utils/openebs-cleanup.yml

- Added openebs component based check for install jobs
- Removed sleep from clean-up job

Added check for specific component in install jobs

---

litmus/director/TCID-DIR-OP-DELETE-CSPC-WITH-NO-VOLUME/README.md
litmus/director/TCID-DIR-OP-DELETE-CSPC-WITH-NO-VOLUME/run_litmus_test.yml
litmus/director/TCID-DIR-OP-DELETE-CSPC-WITH-NO-VOLUME/test.yml
litmus/director/TCID-DIR-OP-DELETE-CSPC-WITH-NO-VOLUME/test_vars.yml

- Delete CSPC created via director which has no volume 
**_Details:_**
- Delete CSPC created via director
- Director should delete the cspc
| --- | --- |
| Application Under Test | Delete CSPC created via director which has no volume  |
| Openebs …

[TCID-DIR-OP-DELETE-CSPC-WITH-NO-VOLUME]:Delete CSPC created via director which has no volume

---

.master-plan.yml

- Changed description for cstor pool deletion jobs

Changed description for cstor pool deletion TC

---

litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-MIRROR/test.yml
litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE/test.yml
litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-MIRROR/test.yml
litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-RAIDZ/test.yml
litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-STRIPE/test.yml
litmus/director/TCID-DIR-OP-DELETE-CSPC-WITH-NO-VOLUME/test.yml

- Added check to get details of bd in cstor pool jobs

Added check to get bd details

---

utils/openebs-cleanup.yml

This PR intends to do the following:
- Add checks for custom resources in openebs-cleanup tasks.
```
```

Add checks for resources in openebs-cleanup task

---

litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-NO-VOLUME/README.md
litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-NO-VOLUME/run_litmus_test.yml
litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-NO-VOLUME/test.yml
litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-NO-VOLUME/test_vars.yml
utils/spc.yml

- Delete SPC via director which has no volume 
**_Details:_**
- Create SPC using yaml
- Invoke API to delete SPC
- Delete SPC via director
- Director should delete the spc
| --- | --- |
| Application Under Test | Delete CSPC created via director which has no volume  |
| Openebs Version | 1.10.0 |
**Notes to reviewer*

[TCID-DIR-OP-DELETE-SPC-WITH-NO-VOLUME]:Delete SPC via director which has no volume

---

testplan/Dockerfile
testplan/sidebars.js

Signed-off-by: bhaskarhc <hcbhaskar7@gmail.com>
```
```

upgrade nodeJs version

---

testplan/sidebars.js

test case name modify

---

testplan/sidebars.js

- TCID-DIR-DMAAS-MINIO-DELETE
- TCID-DIR-GUI-OPENEBS-COMPONENTS-VERSION

Add testCases in sidebar

---

litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE/run_litmus_test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE/test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE/run_litmus_test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE/test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS/test.yml
litmus/director/TCID-DIR-OP-RE-INSTALL-OPENEBS/test.yml

- Changed controlplane and dataplane test from basic installation to advance.
- Remove label node task from basic installation jobs.

Changed labeling logic for controlplane and dataplane components

---

testplan/docs/director/authentication/TCID-GUI-AUTH.md
testplan/docs/director/authentication/TCID-GUI-CLUSTER.md
testplan/docs/director/authentication/TCID-GUI-DASHBOARD.md
testplan/docs/director/authentication/TCID-GUI-PROFILE.md
testplan/docs/director/installation/TCID-DIR-INSTALL-ON-LOCAL-HP.md
testplan/docs/openebs-enterprise/OPENEBS-CHAOS/TCID-CSTOR-BUSYBOX-APP-KILL.md
testplan/docs/openebs-enterprise/OPENEBS-CHAOS/TCID-CSTOR-TARGET-KILL.md
testplan/docs/openebs-enterprise/OPENEBS-CHAOS/TCID-JIVA-BUSYBOX-KILL.md
testplan/docs/openebs-enterprise/OPENEBS-CHAOS/TCID-JIVA-CONTROLLER-KILL.md
testplan/docs/openebs-enterprise/OPENEBS-CHAOS/TCID-JIVA-CONTROLLER-NETWORK-DELAY.md
testplan/docs/openebs-enterprise/OPENEBS-CHAOS/TCID-JIVA-MULTIPLE-REPLICAS-FAILURE.md
testplan/docs/openebs-enterprise/OPENEBS-CHAOS/TCID-JIVA-REPLICA-NETWORK-DELAY.md
testplan/docs/openebs-enterprise/OPENEBS-CHAOS/TCID-JIVA-REPLICA-NODE-AFFINITY.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-CSTOR-CLONE-CREATE.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-CSTOR-SNAPSHOT-CREATE.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-CSTOR-VOLUME-EXT4-RESIZE.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-CSTOR-VOLUME-XFS-RESIZE.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-JIVA-APP-TARGET-AFFINITY.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-JIVA-SNAPSHOT-CREATE.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-JIVA-VOLUME-SCALEUP.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-LOCALPV-HOSTPATH-CREATE.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-LOCALPV-RANDOM-DEVICE-CREATE.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-LOCALPV-SELECTED-DEVICE-CREATE.md
testplan/sidebars.js

https://github.com/mayadata-io/oep-e2e/issues/596#issuecomment-637311495
- Openebs functional 
- Openebs chaos
Add above new stages and GUI test cases

Add test cases

---

litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE/test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE/test.yml

- Earlier we were sending multiple post request for labeling the node which was not the correct way.
- In this PR we are labeling node using one post request.

Changed format of post request for labelling node

---

litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE/test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE/test.yml

- Added check for label in control and data plane install test case

Added check to wait untill label value is reflected in API.

---

testplan/docs/director/openebs-provisioning/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-RAIDZ.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-RAIDZ.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-MIRROR-REBOOT-NODE.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-INSTALL-OPENEBS-LIMIT-RESOURCE.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-INSTALL-OPENEBS.md
testplan/docs/director/openebs-provisioning/TCID-DIR-OP-RE-INSTALL-OPENEBS.md

Added test result link in the test plan site

---

.master-plan.yml

- Added separate sections for OpenEBS functional and chaos jobs.
- Included all the functional and chaos jobs along with their respective details.

testplan(yaml): add openebs functional and chaos tests into testplan

---

litmus/director/cluster-connect-check/test.yaml

- Increased retries for client component check

Increased retries for client component check

---

litmus/director/TCID-DIR-OP-DELETE-CSPC-WITH-VOLUME/README.md
litmus/director/TCID-DIR-OP-DELETE-CSPC-WITH-VOLUME/run_litmus_test.yml
litmus/director/TCID-DIR-OP-DELETE-CSPC-WITH-VOLUME/test.yml
litmus/director/TCID-DIR-OP-DELETE-CSPC-WITH-VOLUME/test_vars.yml

- Delete CSPC created via director which has volume 
**_Details:_**
- Delete CSPC created via director
- Director should not delete the cspc
- Negative test case
| --- | --- |
| Application Under Test | Delete CSPC created via director which has volume  |
|Application …

[TCID-DIR-OP-DELETE-CSPC-WITH-VOLUME]:Delete CSPC created via director which has volume

---

litmus/director/TCID-DIR-OP-DELETE-CSPC-WITH-NO-VOLUME/run_litmus_test.yml
litmus/director/TCID-DIR-OP-DELETE-CSPC-WITH-NO-VOLUME/test_vars.yml

Changed job name for Delete CSPC created via director which has no volume

---

litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-NO-VOLUME/test.yml

Fix for Delete SPC via director which has no volume

---

testplan/docs/director/installation/TCID-DIR-INSTALL-ON-LOCAL-HP.md

Add details on TCID-DIR-INSTALL-ON-LOCAL-HP testCase

---

testplan/docs/kubera-e2e-release-1.10.md
testplan/sidebars.js

chore(release): add kubera 1.10 release notes

---

testplan/docs/kubera-e2e-release-1.10.md

chore(release): update release notes on kubera 1.10

---

litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-NO-VOLUME/test.yml

- Fetching node name using block device

Fetching node name using blockdevice

---

utils/spc.yml

Changed ns for cspc

---

litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-NO-VOLUME/test.yml
utils/cspc.yml

Added namespace for cspc yaml

---

testplan/docs/testbed.md

This PR adds cluster details on the testbed.

Update C2 details and add C3 details for Konvoy

---

.master-plan.yml

- Included cstor-volume replica scaleup and scaledown scenarios under functional job
- Included cstor specific chaos scenarios

include cstor functional and chaos scenarios

---

litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-VOLUME/template/sc.yml

- Changed sc yaml for delete spc with volume test case.

Changed storage class yaml for delete spc with volume test case

---

testplan/docs/compatibility.md
testplan/docs/platforms.md

Update k8s and kubera version in platform details page

---

litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-RAIDZ-REBOOT-NODE/run_litmus_test.yml

Removed typo from job spec

---

litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE/run_litmus_test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE/test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE/test_vars.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE/run_litmus_test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE/test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE/test_vars.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-LIMIT-RESOURCE/run_litmus_test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-LIMIT-RESOURCE/test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-LIMIT-RESOURCE/test_vars.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS/run_litmus_test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS/test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS/test_vars.yml
litmus/director/TCID-DIR-OP-RE-INSTALL-OPENEBS/run_litmus_test.yml
litmus/director/TCID-DIR-OP-RE-INSTALL-OPENEBS/test.yml
litmus/director/TCID-DIR-OP-RE-INSTALL-OPENEBS/test_vars.yml

- This PR helps in fetching latest templateid which will always install latest openebs

Fetching latest templateid to install latest openebs via director

---

.master-plan.yml
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-ZFS-LOCALPV-PROVISIONER.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-ZFS-VOL-RESIZE-EXT4.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-ZFS-VOL-RESIZE-XFS.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-ZFS-VOL-RESIZE-ZFS.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-ZFSPV-CUSTOM-TOPOLOGY-VERIFY.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-ZFSPV-PROPERTY-MODIFY-EXT4.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-ZFSPV-PROPERTY-MODIFY-XFS.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-ZFSPV-PROPERTY-MODIFY-ZFS.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-ZFSPV-SNAPSHOT-CLONE-EXT4-CREATE.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-ZFSPV-SNAPSHOT-CLONE-XFS-CREATE.md
testplan/docs/openebs-enterprise/OPENEBS-FUNCTIONAL/TCID-ZFSPV-SNAPSHOT-CLONE-ZFS-CREATE.md

- Added ZFS Local PV specific scenarios in gitlab-ci.
- Created readme file for each test case. I will update the test procedure and expected results later

add zfs localpv cases into testplan

---

testplan/docs/compatibility.md

Signed-off-by: Aman Gupta <aman.gupta@mayadata.io>
- This PR adds details for c3_cluster of konvoy-e2e pipeline in compatibility.md file

chore(doc): Added c3_cluster details for konvoy-e2e platform

---

litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE/test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE/test.yml

This PR intends to add a label check from API post label cleanup task in the following test cases - 
- TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE
- TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE
```
```

chore(check): add label check post label cleanup task

---

litmus/director/TCID-DIR-OP-INSTALL-OPENEBS/test_vars.yml

fix typo in test_vars file for openebs-components-check

---

.master-plan.yml

- Remove duplicate TCID's for openebs data plane upgrdae 

Removed duplicate TCID's for opnebebs data plane upgrade

---

.master-plan.yml

- Added openebs control plane test case in master plan.

Added openebs control plane upgrade test case id in master plan

---

.master-plan.yml

Signed-off-by: Aman Gupta <aman.gupta@mayadata.io>
- Renamed the tcid to be same with the tcid in gitlab-ci yaml
- Added openebs-storage policies tcid in master plan

renamed the csi volume scaling test in master plan

---

litmus/director/TCID-DIR-OP-OPENEBS-UPGRADE-CP/run_litmus_test.yml
litmus/director/TCID-DIR-OP-OPENEBS-UPGRADE-CP/test_vars.yml

Openebs upgrade fix passed variable to job

---

litmus/director/TCID-DIR-OP-OPENEBS-UPGRADE-CP/test.yml

Added task to check openebs pods and containers status

---

testplan/docs/kubera-e2e-release-1.11.md
testplan/sidebars.js

chore(release): add Kubera-1.11 release notes

---

litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-VOLUME/template/minio-manifest/minio-svc.yaml

- Changed port of minio-svc for TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-VOLUME job

Changed port of minio application

---

.master-plan.yml

Signed-off-by: Aman Gupta <aman.gupta@mayadata.io>
- Adding new tcid for reconciliation test of localpv provisioning on selected device

adding tcid for reconciliation test of localpv provisioning on selected device

---

litmus/director/TCID-DIR-OP-OPENEBS-UPGRADE-CP/test.yml

- Added delays and retries after upgrading control plane components of openebs via director.

Added retries to check for upgraded version of openebs components

---

litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-LIMIT-RESOURCE/run_litmus_test.yml
litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-LIMIT-RESOURCE/test.yml

- Added cleanup task in test script.
- Added env variable to exclude disk : /dev/sdb
Issue: 
https://github.com/mayadata-io/oep-e2e/issues/844

Added cleanup task and EXCLUDE_DEVICE_FILTER env variable in test script

---

litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-LIMIT-RESOURCE/test.yml

Removed Jinja template from failed_when condition in test file

---

litmus/director/TCID-DIR-OP-UPGRADE-CSTOR-POOL/README.md
litmus/director/TCID-DIR-OP-UPGRADE-CSTOR-POOL/run_litmus_test.yml
litmus/director/TCID-DIR-OP-UPGRADE-CSTOR-POOL/test.yml
litmus/director/TCID-DIR-OP-UPGRADE-CSTOR-POOL/test_vars.yml

- Upgrade cstor pool via director.
**_Details:_**
- Create pool using director
- Invoke API to upgrade pools to latest version
- Negative test case
- pool should get upgraded to latest version.
| --- | --- |
| Application Under Test | [TCID-DIR-OP-UPGRADE-CSTOR-POOL]: Upgrade cstor pool via director  |
| Openebs Version | 1.12.0 |
**Notes to reviewer*

[TCID-DIR-OP-UPGRADE-CSTOR-POOL]: Upgrade cstor pool via director

---

testplan/docs/pipelines.md
testplan/package-lock.json

Signed-off-by: prabhatkumarthakur <prabhat.thakur@cloudbyte.com>
```
```

Added steps about how to change the image in Gitlab environment variable

---

litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-LIMIT-RESOURCE/test.yml

Fix for POST request of labelling node

---

litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-LIMIT-RESOURCE/test.yml

- Labeling node 6 in Konvoy and Rancher

Label node-6 for RANCHER and KONVOY before openebs installation

---

litmus/director/TCID-DIR-OP-UPGRADE-CSTOR-POOL/test.yml

- Removed typo from test script of pool upgrade

Removed typo from test script of pool upgrade

---

utils/openebs-label-cleanup.yml

Signed-off-by: Harsh Shekhar <harsh.shekhar@mayadata.io>
This PR intends to refactor openebs-label cleanup util.
```
```

chore(refactor): openebs-label cleanup util

---

testplan/docs/openebs-install/openebs-install.md
testplan/docs/openebs-upgrade/openebs-upgrade.md

- Added cluster details in testplan site

(testplan):Added cluster details for openebs install test cases in testplan site

---

testplan/docs/troubleshooting/VMware_troubleshooting.md
testplan/sidebars.js

- Added a doc with vmware troubleshooting content.
- Updated sidebar file accordingly.
The plan is to keep updating the challenges into this doc whenever we face any issues.

feat(doc):add troubleshooting doc for vmware based challenges

---

testplan/docs/kubera-e2e-release-1.12.md
testplan/docs/troubleshooting/vmware.md
testplan/sidebars.js

feat(release): add release notes for kubera-1.12

---

.master-plan.yml

- added csi based functional test cases into masterplan

[skip ci]: added csi based functional test cases into masterplan

---

testplan/docs/kubera-e2e-release-2.0.md
testplan/sidebars.js

build(release): add E2E release notes for Kubera 2.0

---

.travis.yml

Signed-off-by: Harsh Shekhar <harsh.shekhar@mayadata.io>
This PR intends to fix the travis image push issue.
```
```

fix(travis): image push issue

---

testplan/docs/kubera-e2e-release-1.12.md
testplan/docs/kubera-e2e-release-2.0.md

fix(release): update release notes for E2E pipelines

---

litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-LIMIT-RESOURCE/run_litmus_test.yml

Signed-off-by: Aman Gupta <aman.gupta@mayadata.io>
- Adding extra device /dev/zd in device exclude filter for ndm configmap

refact(yaml): added device in exclude filter for ndm config

---

litmus/director/cluster-connect-check/test_vars.yml

- 'fluentd-aggregator','fluentd-forwarder' pods check remove !
https://github.com/mayadata-io/director/issues/697

remove fluentd pods status check

---

litmus/director/cluster-connect-check/test_vars.yml

Remove maya-system namespace pods checks,
- 'weave-scope-agent',
- 'weave-scope-app',
- 'weave-scope-cluster-agent'
issue : 
https://github.com/mayadata-io/director/issues/697

remove weavescope checks from pipeline

---

litmus/director/cluster-connect-check/test.yaml
litmus/director/cluster-connect-check/test_vars.yml

Signed-off-by: bhaskarhc <hcbhaskar7@gmail.com>
```
```

remove checks of {'kube-state-metrics'} pods
