mayadata-io/oep-e2e

- litmus/director/upgrade-replica-pod-pending/run_litmus_test.yml
- litmus/director/upgrade-replica-pod-pending/test.yml
- litmus/director/upgrade-replica-pod-pending/test_vars.yml
- Upgrade control plane components when one replica pod is not running.
**_Details:_**
- Check whether application volumes are in running state or not.
-  To send one application volume replica to pending state just taint the node with `l=b:NoSchedule`
-  Now delete the particular pod which was present in that node.
- Now replica pod will go into `pending` state.
- After pod went to pending state try to upgrade control plane components.
- It should give error code `405` and the test case will pass when it gives response status code `405`
**Folder Added:** …
> [iuod28]Upgrade the application with 3 replicas when one replica pod is not running

- litmus/director/upgrade-all-replica-pod-pending/run_litmus_test.yml
- litmus/director/upgrade-all-replica-pod-pending/test.yml
- litmus/director/upgrade-all-replica-pod-pending/test_vars.yml
- Upgrade control plane components when all replica pod is not running.
**_Details:_**
- Check whether application volumes are in running state or not.
-  To send all application volume replica to pending state just taint the nodes with `l=b:NoSchedule`
-  Now delete the pod which was present in that node.
- Now all replica pod will go into `pending` state.
- After all pod went to pending state try to upgrade control plane components.
- It should give error code `405` and the test case will pass when it gives response status code `405`
**Folder Added:** …
> [iuod30]:Upgrade the application with 3 replicas when all replica pod is not running

- litmus/director/openebs-control-plane-test/test.yml
- litmus/director/openebs-control-plane-test/test_vars.yml
- litmus/director/openebs-data-plane-test/test.yml
- litmus/director/openebs-data-plane-test/test_vars.yml
- litmus/director/openebs-install/test.yml
- litmus/director/openebs-install/test_vars.yml
- litmus/director/openebs-self-install/test.yml
- litmus/director/openebs-self-install/test_vars.yml
- utils/openebs-cleanup.yml
- utils/openebs-label-cleanup.yaml
Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>
**_This PR is for:_**
- Adding openebs cleanup task in the tests and cleaning up node labels of the cluster
**_Details:_**
- This cleanup task will try to reset the changes that occurred due to different actions in our test. It is important and mandatory to reset the changes after each and every test so that the upcoming test gets a clean environment and does not get affected due to any of the previous tests.
> (big-fix): Adding openebs cleanup task in the tests and cleaning up node labels of the cluster

- litmus/director/openebs-reinstallation/README.md
- litmus/director/openebs-reinstallation/run_litmus_test.yml
- litmus/director/openebs-reinstallation/test.yml
- litmus/director/openebs-reinstallation/test_vars.yml
Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>
**_This PR is for:_**
- Install OpenEBS on a machine already OpenEBS is installed with same version using operator.yaml
**_Details:_**
- This issue is for writing the test cases for getting an appropriate warning when a user tries to install openebs in a cluster where it is already installed. As openebs do not support this feature so when a user tries to install he/she will receive an error with status code `405` which will be telling Openebs is already installed. We should not fail the task like this we will be giving warning to the user that the openebs in already installed if the user wants to install it again then he should delete/remove the previously installed openebs and try again.
> [iuoi06]: Install OpenEBS on a machine already OpenEBS is installed with same version using operator.yaml

- litmus/director/tcid-iuod24-pool-upgrade-one-pod-not-running/README.md
- litmus/director/tcid-iuod24-pool-upgrade-one-pod-not-running/run_litmus_test.yml
- litmus/director/tcid-iuod24-pool-upgrade-one-pod-not-running/test.yml
- litmus/director/tcid-iuod24-pool-upgrade-one-pod-not-running/test_vars.yml
- Upgrade the pools  when one pool pod is not running.
**_Details:_**
-  To send one application pool replica to pending state just change the image of the deployment.
- Now replica pod will go into `pending` state.
- After pod went to pending state try to upgrade control plane components.
- It should give error code `405` and the test case will pass when it gives response status code `405`
| --- | --- |
|Assumptions | openebs should be already …
> [tcid:iuod24]Upgrade the pools  when one pool pod is not running

- litmus/director/tcid-iuod23-pool-upgrade-all-pod-running/README.md
- litmus/director/tcid-iuod23-pool-upgrade-all-pod-running/run_litmus_test.yml
- litmus/director/tcid-iuod23-pool-upgrade-all-pod-running/test.yml
- litmus/director/tcid-iuod23-pool-upgrade-all-pod-running/test_vars.yml
- Upgrade the application with 3 replicas when all pool pod are  running
**_Details:_**
-  Check whether all the control plane components and data plane components are in running state or not.
- Upgrade the control plane components first.
- After upgarding control plane components succesfully upgrade data plane components.
| --- | --- |
|Assumptions | openebs should be already installed with version less then 1.7.0 |
|| cStor pools should be …
> [tcid:iuod23]Upgrade the application with 3 replicas when all pool pods are running

- litmus/director/admin-cluster-connect/run_litmus_test.yml
- litmus/director/admin-cluster-connect/test.yaml
- litmus/director/admin-cluster-connect/test_vars.yml
**Description:**
- This pr contains `admin-cluster-connect` job 
- This job will create configmap `admin-groupid` and `admin-clusterid` for self connect cluster.
**[Logs]**
[admin-job-logs.txt](https://github.com/mayadata-io/oep-e2e/files/4352827/admin-job-logs.txt)
> Added support to get cluster_id of self-connected cluster

- litmus/director/admin-create-apikey/run_litmus_test.yml
- litmus/director/admin-create-apikey/test.yaml
- litmus/director/admin-create-apikey/test_vars.yml
Signed-off-by: harshita-sharma011 <harshita.sharma@mayadata.io>
```
```
Logs:
```
PLAY [localhost] ***************************************************************
TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]
TASK [include_tasks] ***********************************************************
included: /ansible-utils/create_testname.yml for 127.0.0.1
TASK [Record test instance/run ID] *********************************************
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [Construct testname appended with runID] **********************************
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was …
```
> create administrator secret for self-connected cluster

- litmus/director/tcid-iuoi01-openebs-self-install/run_litmus_test.yml
- litmus/director/tcid-iuoi01-openebs-self-install/test.yml
> (fix):Fetch cluster_id from configmap admin-clusterid and group_id from configmap admin-groupid

- litmus/director/account-access/project-account/run_litmus_test.yml
- litmus/director/account-access/project-account/test.yaml
- litmus/director/account-access/project-account/test_vars.yml
- litmus/director/account-access/test_vars.yml
Signed-off-by: harshita-sharma011 <harshita.sharma@mayadata.io>
Test cases added:
- Inside a ProjectAccount you will get all clusters applications.
- Inside a ProjectAccount you will get all clusters storage pools. 
-  `director-user-pass` secret is already created on the cluster
-  some sts or deployments are running on the cluster
```
```
Logs:
```
PLAY [localhost] ***************************************************************
TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]
TASK [include_tasks] ***********************************************************
included: /ansible-utils/create_testname.yml for 127.0.0.1
TASK [Record test instance/run ID] …
```
> adding project account resources access

- litmus/director/account-access/cluster-account/run_litmus_test.yml
- litmus/director/account-access/cluster-account/test.yaml
- litmus/director/account-access/cluster-account/test_vars.yml
- litmus/director/account-access/test_vars.yml
Signed-off-by: harshita-sharma011 <harshita.sharma@mayadata.io>
Test cases added:
- Inside a ClusterAccount you will get all cluster specific storage pools. 
-  Inside a ClusterAccount you will get all cluster specific applications.
-  `director-user-pass` secret is already created on the cluster
-  some sts or deployments are running on the cluster
```
```
Logs: 
```
PLAY [localhost] ***************************************************************
TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]
TASK [include_tasks] ***********************************************************
included: /ansible-utils/create_testname.yml for 127.0.0.1
TASK [Record test instance/run ID] …
```
> add cluster account resources test cases

- litmus/director/tcid-rec01-list-recommendations/run_litmus_test.yml
- litmus/director/tcid-rec01-list-recommendations/test.yml
- litmus/director/tcid-rec01-list-recommendations/test_vars.yml
- List recommendation and capacity recommendations.
**_Details:_**
`body: …
> (tcid-rec01):List capacity recommendations

- litmus/director/tcid-rec02-device-recommendation/run_litmus_test.yml
- litmus/director/tcid-rec02-device-recommendation/test.yml
- litmus/director/tcid-rec02-device-recommendation/test_vars.yml
- List device recommendations.
**_Details:_**
- By the help of this `recommendation_id` **POST** request on url `'{{ director_url }}/v3/groups/{{ group_id }}/{{ recommendation_id }}/?action=getdevicerecommendation'` by this GET request you will get list of device recommendations
`body: '{"clusterId":"{{ …
> tcid-rec02:List Device recommendations

- litmus/director/tcid-iuoi01-openebs-self-install/run_litmus_test.yml
- litmus/director/tcid-iuoi01-openebs-self-install/test.yml
- Changed secret name from `director-user-pass` to `director-admin-pass`
- And also removed clean-up of openebs because in self install cluster we are not installing openebs.
**Special Note For Reviewer:** 
**[REFER FOR SECRET]** https://github.com/mayadata-io/oep-e2e/pull/289/files
> (FIX):Changed secret name for self-connect cluster and removed openesb clean-up task

- litmus/director/tcid-iuoi02-openebs-install/test.yml
- Passing namespace to the openebs-cleanup.yml at the last of the job to remove openebs.
> (Bug):Passing namespace to the openebs-cleanup.yml

- litmus/director/tcid-ppcp01-create-cstor-pool/README.md
- litmus/director/tcid-ppcp01-create-cstor-pool/run_litmus_test.yml
- litmus/director/tcid-ppcp01-create-cstor-pool/test.yml
- litmus/director/tcid-ppcp01-create-cstor-pool/test_vars.yml
- Create cstor pool using recommendations
**_Details:_**
`body: '{"clusterId":"{{ …
> [tcid-ppcp01] Create cstor pool using recommendations

- utils/result_update.py
This PR intends to refactor `result_update.py` script to add a Platform column in test results table.
```
```
> chore(refactor): add platform column in test results table

- litmus/director/maya-io-server/test.yaml
This PR fixes the path to read the director-url which is being used in getting it's value.
> fix path for director-url

- litmus/director/tcid-iuoc02-control-plane-upgrade-operator-yml/README.md
- litmus/director/tcid-iuoc02-control-plane-upgrade-operator-yml/run_litmus_test.yml
- litmus/director/tcid-iuoc02-control-plane-upgrade-operator-yml/test.yml
- litmus/director/tcid-iuoc02-control-plane-upgrade-operator-yml/test_vars.yml
- Upgrade OpenEBS installed using operator.yaml(Not using Director) 
**_Details:_**
**_Steps involved:_**
- Also check the status of all the Data-Plane and Control-Plane components they should be in running state.
**Steps involved in the test case**
- Get active openebs record from v3/groups/{gropu_id}/cluster/{cluster_id}/openebs/{openebs_id}
- After that trigger action upgradecontrolplane. Once we triggered the action with the target version as input.
- This should result into a `InvalidAction`
- Control plane upgrade should not proceed.
| --- | --- |
|Assumptions | openebs should be already installed with …
> [tcid-iuoc02]Upgrade OpenEBS installed using operator.yaml(Not using Director)

- api_testing/cluster/cluster.py
This PR intends to increase the time for which the connected cluster state is checked.
```
```
> Increase time for checking cluster active state

- litmus/director/TCID-DIR-OP-CSP-REC-CREATE-MIRROR/README.md
- litmus/director/TCID-DIR-OP-CSP-REC-CREATE-MIRROR/run_litmus_test.yml
- litmus/director/TCID-DIR-OP-CSP-REC-CREATE-MIRROR/test.yml
- litmus/director/TCID-DIR-OP-CSP-REC-CREATE-MIRROR/test_vars.yml
- Verify creation of mirror cstor pool cluster
**_Details:_**
`body: …
> [TCID-DIR-OP-CSP-REC-CREATE-MIRROR]Verify creation of mirror cstor pool cluster

- litmus/director/TCID-DIR-OP-CSP-REC-LIST-MIRROR/README.md
- litmus/director/TCID-DIR-OP-CSP-REC-LIST-MIRROR/run_litmus_test.yml
- litmus/director/TCID-DIR-OP-CSP-REC-LIST-MIRROR/test.yml
- litmus/director/TCID-DIR-OP-CSP-REC-LIST-MIRROR/test_vars.yml
- Verify List of Mirror Recommendations
**_Details:_**
`body: '{"clusterId":"{{ …
> [TCID-DIR-OP-CSP-REC-LIST-MIRROR]Verify List of Mirror Recommendations

- litmus/director/tcid-iuod25-pool-upgrade-two-pod-not-running/README.md
- litmus/director/tcid-iuod25-pool-upgrade-two-pod-not-running/run_litmus_test.yml
- litmus/director/tcid-iuod25-pool-upgrade-two-pod-not-running/test.yml
- litmus/director/tcid-iuod25-pool-upgrade-two-pod-not-running/test_vars.yml
- Upgrade the pools  when two pool pods are not running.
**_Details:_**
-  To send one application pool replica to pending state just change the image of the deployment.
- Now replica pod will go into `pending` state.
- After pod went to pending state try to upgrade control plane components.
- It should give error code `405` and the test case will pass when it gives response status code `405`
| --- | --- |
|Assumptions | openebs should be already …
> [tcid-iuod25]Upgrade the application with 3 replicas when two pool pods are in pending state

- utils/result_update.py
This PR intends to fix job URL in result table.
```
```
> Make job url generic for all platforms in result table

- litmus/director/tcid-iuoi14-openebs-resource-limit-installation/test.yml
- Removed openebs cleanup task from openebs-resource-limit-installation job
- We removed openebs clean-up from this job because we need to use openebs for creating cstorpools in cluster3
> Removed openebs cleanup task from openebs-resource-limit-installation job

- api_testing/cluster/cluster.py
This PR intends to increase retries for checking connected cluster state. The retry time needs to be increased further as the cluster connect is taking some more tiime for on premise clusters.
```
```
> Increase no of retries for checking cluster state

- litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-RAIDZ/README.md
- litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-RAIDZ/run_litmus_test.yml
- litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-RAIDZ/test.yml
- litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-RAIDZ/test_vars.yml
- List raidz based cstor pool recommendations
**_Details:_**
- Director should list the supported recommendations without error
- Director should list the capacity based recommendations without error
- Director should list the device based recommendations without error
| --- | --- |
| …
> [TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-RAIDZ]:List raidz based cstor pool recommendations

- litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-RAIDZ/README.md
- litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-RAIDZ/run_litmus_test.yml
- litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-RAIDZ/test.yml
- litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-RAIDZ/test_vars.yml
- Verify creation of raidz cstor pool cluster
**_Details:_**
`body: …
> [TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-RAIDZ]:Verify creation of raidz cstor pool

- litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE/test.yml
This PR intends to increase time interval for checking cstor pool creation job in `TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE`
```
```
> Increase time interval for checking cstor pool creation job

- litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-RAIDZ-REBOOT-NODE/README.md
- litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-RAIDZ-REBOOT-NODE/test.yml
- litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-RAIDZ-REBOOT-NODE/test_litmus_test.yml
- litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-RAIDZ-REBOOT-NODE/test_vars.yml
- Verify raidz cstor pool cluster after node reboot
**_Details:_**
- Invoke API to create raidz cstor pool cluster
- Reboot node and then verify the status of pools
- Director should list the supported recommendations without error
- Director should list the capacity based recommendations without error
- Director should list the device based recommendations without error
| Title | …
> [TCID-DIR-OP-CSTOR-POOL-RECOMMEND-RAIDZ-REBOOT-NODE]:Verify raidz cstor pool cluster after node reboot

- litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-NO-VOLUME/README.md
- litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-NO-VOLUME/run_litmus_test.yml
- litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-NO-VOLUME/test.yml
- litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-NO-VOLUME/test_vars.yml
- utils/cspc.yml
- Delete CSPC not created via director which has no volume 
**_Details:_**
- Create CSPC using yaml
- Invoke API to delete CSPC
- Delete CSPC via director
- Director should delete the cspc
| --- | --- |
| Application Under Test | Delete CSPC not created via director which has no volume   |
| Openebs Version | 1.10.0 |
**Notes to reviewer*
> [TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-NO-VOLUME]Delete CSPC not created via director which has no volume

- litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-VOLUME/README.md
- litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-VOLUME/run_litmus_test.yml
- litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-VOLUME/template/minio-manifest/minio-official.yaml
- litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-VOLUME/template/minio-manifest/minio-pvc.yaml
- litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-VOLUME/template/minio-manifest/minio-svc.yaml
- litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-VOLUME/template/sc.yml
- litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-VOLUME/template/spc.yml
- litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-VOLUME/test.yml
- litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-VOLUME/test_vars.yml
- Delete SPC via director which has volume 
**_Details:_**
- Create SPC using yaml
- Invoke API to delete SPC
- Delete SPC via director and it will give 405 error because application is using that pools in this test case.
- Negative test case
- Director should not delete the spc
| --- | --- |
| Application Under Test | Delete CSPC created via director which has volume  |
| Openebs …
> [TCID-DIR-OP-DELETE-SPC-WITH-VOLUME]:Delete SPC via director which has volume

- Dockerfile
The following PR intends to do the following:
- Add install aws-cli version 2 and aws-iam-authenticator in the Dockerfile.
```
```
> Add aws-cli and aws-iam-authenticator in litmus job image

- litmus/director/TCID-DIR-OP-DELETE-SPC-WITH-VOLUME/test.yml
- Earlier we were fetching the bd from any of the node so sometimes's it was taking disk which was attached to master node because of that sometimes application using bd was getting stuck in ContainerCreating state.
- This PR helps in fetching the bd which is not attached to master node.
> Get the bd which is not attached to master node to create SPC

- litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE/test.yml
- litmus/director/TCID-DIR-OP-INSTALL-OPENEBS/test.yml
This PR intends to do the following:
- Check node details of the cluster on which we want to install openebs. If the node details is empty retry until it gets updated with all the details.
- Fix label cleanup task.
```
```
> fix(openebs-install): check node details of the cluster

- litmus/director/TCID-DIR-OP-INSTALL-OPENEBS/test.yml
- litmus/director/TCID-DIR-OP-INSTALL-OPENEBS/test_vars.yml
This PR separates the check on OpenEBS Daemonsets by checking the count of labelled nodes and the DS pods.
> Update check to verify state of openebs components

- litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-VOLUME/run_litmus_test.yml
- litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-VOLUME/template/minio-manifest/minio-official.yaml
- litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-VOLUME/template/minio-manifest/minio-pvc.yaml
- litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-VOLUME/template/minio-manifest/minio-svc.yaml
- litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-VOLUME/template/sc.yml
- litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-VOLUME/test.yml
- litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-VOLUME/test_vars.yml
- CSPC not created via director which has volume
**_Details:_**
- Create CSPC using yaml
- Invoke API to delete SPC
- Delete CSPC via director and it will give 405 error because application is using that pools in this test case.
- Negative test case
- Director should not delete the spc
| --- | --- |
| Application Under Test | CSPC not created via director which has volume  |
| Openebs …
> [TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-VOLUME]:Delete CSPC not created via director which has volume

- litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-NO-VOLUME/test.yml
- litmus/director/TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-VOLUME/test.yml
- Sometimes filesystem is getting created into the master node blockdevices. 
- And when we are using that device we are getting an error saying.
```
TASK [Create CSPC] *************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "kubectl create -f /utils/cspc.yml", "delta": "0:00:00.184331", "end": "2020-07-16 07:47:28.302378", "msg": "non-zero return code", "rc": 1, "start": "2020-07-16 07:47:28.118047", "stderr": "Error from server (BadRequest): error when creating \"/utils/cspc.yml\": admission webhook \"admission-webhook.cstor.openebs.io\" denied the request: invalid cspc specification: invalid pool spec: block device has file system {ext4}", "stderr_lines": ["Error from server (BadRequest): error when creating …
```
> Refactored logic to select blockdevice which is unclaimed and does not contain any file system into it

- litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-MIRROR/test.yml
- litmus/director/TCID-DIR-OP-RE-INSTALL-OPENEBS/test.yml
- This PR includes task which checks for the openebs entry in openebses entry.
- After installing openebs this task will check for the openebs `Active` entry.
- This task will retry for 2 minutes after installing opnebs for openebses active entry.
- I have also added 2 min sleep before creating cstor pool
> Added check to verify openebs is installed or not via API

- .travis.yml
- Travis build is failing for testplan site due to some change in docusaurus. Due to this travis ci is failing for oep-e2e repo.
- We are removing the code for testplan build till docusaurus issue fixed.
> Removing travis build code for testplan

- litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-LIMIT-RESOURCE/run_litmus_test.yml
- Added few more path values in `EXCLUDE_DEVICE_FILTER` from the ndm configmap and these disk will not be used as a block-device for openebs related test cases.
> Added few more path in EXCLUDE_DEVICE_FILTER to so that these disks are not used to create BD

- testplan/docs/troubleshooting/aws.md
- testplan/docs/troubleshooting/konvoy.md
- testplan/docs/troubleshooting/rancher.md
- testplan/sidebars.js
Signed-off-by: Harsh Shekhar <harsh.shekhar@mayadata.io>
This PR intends to do the following:
- Add `Troubleshooting` section in testplan site.
- Add Rancher troubleshooting docs.
```
```
> feat(testplan): add troubleshooting section in testplan

- litmus/director/TCID-DIR-OP-INSTALL-OPENEBS-LIMIT-RESOURCE/test.yml
- Added 10 seconds sleep after node labeling task so that the installation of openebs should not get failed.
- Added one post openebs install check to verify openebs is installed on cluster via API
> (Fix):Added sleep after labelling node in Resource limit openebs installation job

- testplan/docs/troubleshooting/vmware.md
- Recently, we came across an issue due to the images present in VM instances while creating snapshot. Updated this info in VMware troubleshooting doc.
> doc(troubleshooting):update vmware doc with an issue due to snapshot

- monitor/actions.go
- monitor/config.go
- monitor/main.go
- monitor/pooling.go
Signed-off-by: <ranjanshashank855@gmail.com>
- Continuously monitor for Gitlab and lab network and performs actions when either is down.
- Script pools for two instances *Gitlab* & *Landing Machine*.
- Following actions are performed when either goes down
- Restore the IP tables if does not exist in landing machine.
- Start the necessary VM by iterating over ESX.
- Restart the Gitlab Runners.
> feat(add): script to monitor lab infra

- .travis.yml
- litmus/director/TCID-DIR-OP-OPENEBS-UPGRADE-CP/test.yml
- This PR intends to fetch `openebs_target_version` from upgradematrixs endpoint.
- Earlier we used to fetch version from openebs templates but due to some change in API now it is recommended to fetch version from upgradematrixs.
- And also added check if `openebs_current_version` is not in `supportedBaseVersions` then it should fail.
- Commented tesplan build steps as the build is failing.
https://github.com/mayadata-io/oep-e2e/issues/886
Please delete options that are not relevant.
> Fetch openebs_target_version from upgradematrixs endpoint to upgrade openebs control plane

- .travis.yml
- testplan/docs/getstarted.md
- testplan/package.json
**travis build fail issue :**
- ./testplan/ build failing because of mismatching of package installing and unable to starting server on `yarn build` build .
**Fix for the issue and changes happend in this PR**
- Issue got fixed by making changes in package.json to install updated packages of Docusauraus .
- Enabled ./testplan/ build in travis
> fix [build] : install Docusaurus latest packages

- Dockerfile
- litmus/director/TCID-KUBELET-RESTART/run_litmus_test.yml
- litmus/director/TCID-KUBELET-RESTART/test.yml
- litmus/director/TCID-KUBELET-RESTART/test_vars.yml
Signed-off-by: Harsh Shekhar <harsh.shekhar@mayadata.io>
This PR intends to do the following:
- Add Kubera chaos test - `TCID-KUBELET-RESTART`.
- Add docker install in Dockerfile.
```
```
> feat(chaos): add kubelet-restart chaos test

- testplan/Dockerfile
Build getting failed because of node version not compatiable with latest node packages ,
```sh
error @ava/babel@1.0.1: The engine "node" is incompatible with this module. Expected version ">=10.18.0 <11 || >=12.14.0 <13 || >=13.5.0". Got "10.16.0"
``
failed build : https://travis-ci.com/github/mayadata-io/oep-e2e/builds/199683619#L6897
> node version update
